### ISSUE TITLE
Add auto syntax-highlighting for code snippets

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/tedium#18]
(I hope this is the correct place for this request)

When reading the autogenerated docs, the snippets are a bit hard to read/extract from the other documentation. Syntax highlighting could help with this problem. The visual difference of the highlighting makes distinguishing code snippets from pure docs easier. It would be nice if the bot could detect these snippets and automatically add &#96;&#96;&#96;HTML in front of it and closes it with &#96;&#96;&#96;.

For example in the `paper-input` docs replace

```
<paper-input-container>
  <input is="iron-input" maxlength="20">
  <paper-input-char-counter></paper-input-char-counter>
</paper-input-container>
```

with

``` HTML
<paper-input-container>
  <input is="iron-input" maxlength="20">
  <paper-input-char-counter></paper-input-char-counter>
</paper-input-container>
```

In markdown code:
&#96;&#96;&#96;HTML
&lt;paper-input-container>
&nbsp;&nbsp;&lt;input is="iron-input" maxlength="20">
&nbsp;&nbsp;&lt;paper-input-char-counter>&lt;/paper-input-char-counter>
&lt;/paper-input-container>
&#96;&#96;&#96;

**Comment by rictic** [comment]
BTW, thanks for filing this bug!

**Comment by TimvdLippe** [comment]
Ow I love this: 

![image](https://cloud.githubusercontent.com/assets/5948271/12298883/9b7ab736-ba14-11e5-8410-540292225cec.png)

Once again thank you for implementing this. This little change makes my life a lot easier :heart:

**Comment by rictic** [comment]
Glad to hear it!
