### ISSUE TITLE
Correction in README

### ISSUE THREAD

**Issue by luvagarwal** [PolymerLabs/tedium#39]
`nvm` written in place of `npm`
https://github.com/PolymerLabs/tedium/edit/master/README.md#L13

**Comment by rictic** [comment]
[nvm](https://github.com/creationix/nvm) is actually what's intended there. tedium is only intended to work with the latest version of the v5 branch of Node.

**Comment by luvagarwal** [comment]
Ah okay! Thanks for the response.
May be you can add a link to nvm in readme?
