### ISSUE TITLE
Commit spam for issue template

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/tedium#43]
It seems the bot is spamming commits again, now with the issue template.

https://github.com/PolymerElements/iron-location/commits/master

Edit: too late for now, but actually I should have reopened #37

**Comment by rictic** [comment]
I believe that it was a misconfiguration I had on the machine that was running this. That should fix it.

Hoo boy that's a bunch of unneeded commits on iron-location though. @azakus Do you think we could do a force push to iron-location#master to remove those unneeded commits?

**Comment by TimvdLippe** [comment]
The commits are too old now to be fixed I suppose. Since this was just a misconfiguration, there is no further action required in this issue.
